Repository locavell/locavel-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#17 [#12] S3 연결 및 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/locavel/apiPayload/exception/GeneralException.java
  src/main/java/com/example/locavel/apiPayload/exception/handler/S3Handler.java
  src/main/java/com/example/locavel/config/S3Config.java
  src/main/java/com/example/locavel/service/S3Uploader.java
Labels: Feat :sparkles:

#19 [#15] 리뷰 이미지 등록 기능 추가
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/exception/handler/ReviewsHandler.java
  src/main/java/com/example/locavel/config/swagger/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/example/locavel/config/swagger/SwaggerConfig.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/domain/ReviewImg.java
  src/main/java/com/example/locavel/domain/Reviews.java
  src/main/java/com/example/locavel/repository/ReviewImgRepository.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/service/S3Uploader.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
Labels: Feat :sparkles:, Docs, Fix

#21 [#20] 리뷰 수정 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: Feat :sparkles:

#23 [#22] 리뷰 삭제 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
Labels: Feat :sparkles:

#25 [#18] 장소 등록, 특정 장소 조회 api 구현
  build.gradle
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/exception/handler/PlacesHandler.java
  src/main/java/com/example/locavel/config/WebClientConfig.java
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/domain/Category.java
  src/main/java/com/example/locavel/domain/Places.java
  src/main/java/com/example/locavel/domain/enums/Category.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/dto/MapDTO/MapResponseDTO.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceRequestDTO.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceResponseDTO.java
Labels: Feat :sparkles:

#27 [#26] 장소 등록 API, Region 수정
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/domain/PlaceImg.java
  src/main/java/com/example/locavel/domain/Places.java
  src/main/java/com/example/locavel/domain/Region.java
  src/main/java/com/example/locavel/domain/enums/Category.java
  src/main/java/com/example/locavel/domain/enums/Region.java
  src/main/java/com/example/locavel/repository/PlaceImgRepository.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceRequestDTO.java
Labels: Feat :sparkles:

#28 [#24] 리뷰 목록 조회 및 리뷰 요약 정보 조회 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/domain/enums/Traveler.java
  src/main/java/com/example/locavel/repository/ReviewRepository.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: Feat :sparkles:

#31 [#30] 장소 목록 조회 API 구현
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/domain/Places.java
  src/main/java/com/example/locavel/domain/enums/Category.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/repository/ReviewRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceResponseDTO.java
Labels: Feat :sparkles:

#36 [#35] 리뷰 상세조회 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/config/SecurityConfig.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/repository/ReviewImgRepository.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: Feat :sparkles:

#33 [#32] 장소 검색 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/config/SecurityConfig.java
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/domain/Places.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceResponseDTO.java
Labels: Feat :sparkles:

#46 [#42] 팔로우 관련 기능 구현
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/apiPayload/exception/handler/FollowHandler.java
  src/main/java/com/example/locavel/converter/FollowConverter.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/domain/Follow.java
  src/main/java/com/example/locavel/domain/User.java
  src/main/java/com/example/locavel/repository/FollowRepository.java
  src/main/java/com/example/locavel/repository/UserRepository.java
  src/main/java/com/example/locavel/service/FollowService.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/FollowRestController.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/FollowDTO/FollowRequestDTO.java
  src/main/java/com/example/locavel/web/dto/FollowDTO/FollowResponseDTO.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: Feat :sparkles:, Fix

#48 [#43]유저 등급 API 구현
  src/main/java/com/example/locavel/LocavelApplication.java
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/config/SecurityConfig.java
  src/main/java/com/example/locavel/converter/UserConverter.java
  src/main/java/com/example/locavel/domain/User.java
  src/main/java/com/example/locavel/domain/enums/Grade.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/service/userService/UserCommandService.java
  src/main/java/com/example/locavel/service/userService/UserCommandServiceImpl.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/controller/UserController.java
  src/main/java/com/example/locavel/web/dto/UserDTO/UserRequestDto.java
  src/main/java/com/example/locavel/web/dto/UserDTO/UserResponseDto.java
Labels: Feat :sparkles:

#55 [#47] 위시리스트 관련 기능 구현
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/converter/FollowConverter.java
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/domain/Places.java
  src/main/java/com/example/locavel/domain/User.java
  src/main/java/com/example/locavel/domain/WishList.java
  src/main/java/com/example/locavel/repository/PlaceImgRepository.java
  src/main/java/com/example/locavel/repository/UserRegionRepository.java
  src/main/java/com/example/locavel/repository/WishListRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/dto/FollowDTO/FollowResponseDTO.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceResponseDTO.java
Labels: Feat :sparkles:, Fix

#58 [#56] 마이페이지 관련 API 구현
  src/main/java/com/example/locavel/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/converter/UserConverter.java
  src/main/java/com/example/locavel/domain/User.java
  src/main/java/com/example/locavel/repository/ReviewRepository.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
  src/main/java/com/example/locavel/web/controller/UserController.java
  src/main/java/com/example/locavel/web/dto/PlaceDTO/PlaceResponseDTO.java
  src/main/java/com/example/locavel/web/dto/UserDTO/UserResponseDto.java
Labels: Feat :sparkles:, Fix

#59 [#57] 내 지역 API 구현
  src/main/java/com/example/locavel/config/SecurityConfig.java
  src/main/java/com/example/locavel/converter/UserConverter.java
  src/main/java/com/example/locavel/domain/User.java
  src/main/java/com/example/locavel/service/NaverMapService.java
  src/main/java/com/example/locavel/service/userService/UserCommandService.java
  src/main/java/com/example/locavel/service/userService/UserCommandServiceImpl.java
  src/main/java/com/example/locavel/web/controller/UserController.java
  src/main/java/com/example/locavel/web/dto/UserDTO/UserResponseDto.java
Labels: Feat :sparkles:

#61 [#60] 여행객/현지인 구분 방식 수정 & Places 생성 시 user 설정
  src/main/java/com/example/locavel/converter/PlaceConverter.java
  src/main/java/com/example/locavel/domain/enums/Traveler.java
  src/main/java/com/example/locavel/service/PlaceService.java
  src/main/java/com/example/locavel/web/controller/PlaceRestController.java
Labels: Fix

#74 cors 에러 관리 추가
  src/main/java/com/example/locavel/config/WebConfig.java
Labels: Fix

#81 fix : 내 지역 설정 필수 에러 메시지 추가
  src/main/java/com/example/locavel/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/locavel/domain/enums/Traveler.java
Labels: Feat :sparkles:, Fix

#85 [#84] 리뷰 등록 controller 수정
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
Labels: Fix

#88 Fix: 리뷰 등록 controller 수정
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
Labels: Fix

#90 [#89] 리뷰 등록 controller 수정
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
Labels: Fix

#91 fix : 리뷰 등록 controller 수정
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
Labels: Fix

#95 [#94] 리뷰 수정 메서드 Put으로 변경
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
Labels: Fix
