Repository locavell/locavel-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#3 [#2] swagger 연동
  build.gradle
  src/main/java/com/example/locavel/config/SwaggerConfig.java
Labels: Feat :sparkles:, Docs

#11 [#10] Places 테이블 및 연관관계 매핑 수정
  src/main/java/com/example/locavel/domain/Places.java
Labels: Feat :sparkles:

#7 CI / CD 환경 세팅
  .DS_Store
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  src/.DS_Store
Labels: Feat :sparkles:

#9 [#8] 리뷰 등록 API 구현
  src/main/java/com/example/locavel/LocavelApplication.java
  src/main/java/com/example/locavel/converter/ReviewConverter.java
  src/main/java/com/example/locavel/domain/Reviews.java
  src/main/java/com/example/locavel/domain/enums/Traveler.java
  src/main/java/com/example/locavel/repository/PlaceRepository.java
  src/main/java/com/example/locavel/repository/ReviewRepository.java
  src/main/java/com/example/locavel/repository/UserRepository.java
  src/main/java/com/example/locavel/service/ReviewService.java
  src/main/java/com/example/locavel/web/controller/ReviewRestController.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewRequestDTO.java
  src/main/java/com/example/locavel/web/dto/ReviewDTO/ReviewResponseDTO.java
Labels: Feat :sparkles:

#14 [#13] swagger 의존성 변경
  build.gradle
Labels: Docs
